name: Build and Push Staging to Docker Hub

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decode .env file and set as environment variables
        run: |
          echo "${{ secrets.ENV_FILE_CONTENT }}" > encoded.env
          base64 -d encoded.env > .env

      - name: Get the current image tag & increment
        run: |
          current_tag="${{ secrets.CURRENT_IMAGE_TAG }}"
          IFS='.' read -ra tag_parts <<< "$current_tag"
          tag_parts[2]=$((tag_parts[2]+1))
          new_tag="${tag_parts[0]}.${tag_parts[1]}.${tag_parts[2]}"
          echo "New tag: $new_tag"
          echo "CURRENT_IMAGE_TAG=$new_tag" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mhari16/books-api:${{ env.CURRENT_IMAGE_TAG }} .

      - name: Push Docker image to Docker Hub
        run: docker push mhari16/books-api:${{ env.CURRENT_IMAGE_TAG }}
